version: '3.9'

services:
  memory_db_redis:
    image: redis:latest
    container_name: memory_db_redis
    ports:
      - "6379:6379"
    healthcheck:  # Define healthcheck for Redis
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  tool_runtime_docker:
    image: docker:24.0.2-dind
    container_name: tool_runtime_docker
    privileged: true
    volumes:
      - docker-data:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=   # Disable Docker TLS
    healthcheck:  # Define healthcheck for Docker
      test: ["CMD", "docker", "ps"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  bff_fastapi_app:
    build:
      context: ./
    container_name: bff_fastapi_app
    depends_on:
      tool_runtime_docker:
        condition: service_healthy
      memory_db_redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    # env_file:
    #   - ./.env
    environment:
      - DOCKER_HOST=tcp://tool_runtime_docker:2375

volumes:
  docker-data: